mysql:
    image: mysql:latest
    ports:
        - "3306:3306"
    container_name: mysql
    restart: always
    volumes:
        - /opt/dev-cluster/CF-Frontend/code:/code
    environment:
        - MYSQL_ROOT_PASSWORD=patrick
